<?xml version="1.0" encoding="utf-8"?><Database Name="HumaneSociety" Class="HumaneSocietyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Desktop-2RUDMAK;Initial Catalog=HumaneSociety;Integrated Security=True" SettingsObjectName="HumaneSociety.Properties.Settings" SettingsPropertyName="HumaneSocietyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Animal_Intake" Member="Animal_Intakes">
    <Type Name="Animal_Intake">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Intake_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Animals_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Intake_Animal_Intake" Member="Intake" ThisKey="Intake_ID" OtherKey="ID" Type="Intake" IsForeignKey="true" />
      <Association Name="Intake_Animal_Intake1" Member="Intake1" ThisKey="Intake_ID" OtherKey="ID" Type="Intake" IsForeignKey="true" />
      <Association Name="Animal_Animal_Intake" Member="Animal" ThisKey="Animals_ID" OtherKey="ID" Type="Animal" IsForeignKey="true" />
      <Association Name="Animal_Animal_Intake1" Member="Animal1" ThisKey="Animals_ID" OtherKey="ID" Type="Animal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address" Member="Address1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Zip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Address_Person" Member="Persons" ThisKey="ID" OtherKey="Address_ID" Type="Person" />
      <Association Name="Address_Person1" Member="Persons1" ThisKey="ID" OtherKey="Address_ID" Type="Person" />
    </Type>
  </Table>
  <Table Name="dbo.Adoption_Info" Member="Adoption_Infos">
    <Type Name="Adoption_Info">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StaffID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Customer_Adoption_Info" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
      <Association Name="Customer_Adoption_Info1" Member="Customer1" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
      <Association Name="Customer_Adoption_Info2" Member="Customer2" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
      <Association Name="Staff_Adoption_Info" Member="Staff" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" />
      <Association Name="Staff_Adoption_Info1" Member="Staff1" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Adoption_Status" Member="Adoption_Status">
    <Type Name="Adoption_Status">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Animal_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Adopted" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Animal_Adoption_Status" Member="Animal" ThisKey="Animal_ID" OtherKey="ID" Type="Animal" IsForeignKey="true" />
      <Association Name="Animal_Adoption_Status1" Member="Animal1" ThisKey="Animal_ID" OtherKey="ID" Type="Animal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Customer_Adoption_Info" Member="Adoption_Infos" ThisKey="ID" OtherKey="CustomerID" Type="Adoption_Info" />
      <Association Name="Customer_Adoption_Info1" Member="Adoption_Infos1" ThisKey="ID" OtherKey="CustomerID" Type="Adoption_Info" />
      <Association Name="Customer_Adoption_Info2" Member="Adoption_Infos2" ThisKey="ID" OtherKey="CustomerID" Type="Adoption_Info" />
      <Association Name="Customer_Intake" Member="Intakes" ThisKey="ID" OtherKey="CustomerID" Type="Intake" />
      <Association Name="Customer_Intake1" Member="Intakes1" ThisKey="ID" OtherKey="CustomerID" Type="Intake" />
      <Association Name="Person_Customer" Member="Person" ThisKey="PersonID" OtherKey="ID" Type="Person" IsForeignKey="true" />
      <Association Name="Person_Customer1" Member="Person1" ThisKey="PersonID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Intake" Member="Intakes">
    <Type Name="Intake">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StaffID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Intake_Animal_Intake" Member="Animal_Intakes" ThisKey="ID" OtherKey="Intake_ID" Type="Animal_Intake" />
      <Association Name="Intake_Animal_Intake1" Member="Animal_Intakes1" ThisKey="ID" OtherKey="Intake_ID" Type="Animal_Intake" />
      <Association Name="Customer_Intake" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
      <Association Name="Customer_Intake1" Member="Customer1" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
      <Association Name="Staff_Intake" Member="Staff" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" />
      <Association Name="Staff_Intake1" Member="Staff1" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Medical_Procedure" Member="Medical_Procedures">
    <Type Name="Medical_Procedure">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnimalID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StaffID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vaccination_Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Spey_Neuter" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Medical_Procedure_Medical_Staff" Member="Medical_Staffs" ThisKey="ID" OtherKey="ProcedureID" Type="Medical_Staff" />
      <Association Name="Medical_Procedure_Medical_Staff1" Member="Medical_Staffs1" ThisKey="ID" OtherKey="ProcedureID" Type="Medical_Staff" />
      <Association Name="Staff_Medical_Procedure" Member="Staff" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" />
      <Association Name="Staff_Medical_Procedure1" Member="Staff1" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" />
      <Association Name="Animal_Medical_Procedure" Member="Animal" ThisKey="AnimalID" OtherKey="ID" Type="Animal" IsForeignKey="true" />
      <Association Name="Animal_Medical_Procedure1" Member="Animal1" ThisKey="AnimalID" OtherKey="ID" Type="Animal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Medical_Staff" Member="Medical_Staffs">
    <Type Name="Medical_Staff">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProcedureID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Medical_Procedure_Medical_Staff" Member="Medical_Procedure" ThisKey="ProcedureID" OtherKey="ID" Type="Medical_Procedure" IsForeignKey="true" />
      <Association Name="Medical_Procedure_Medical_Staff1" Member="Medical_Procedure1" ThisKey="ProcedureID" OtherKey="ID" Type="Medical_Procedure" IsForeignKey="true" />
      <Association Name="Staff_Medical_Staff" Member="Staff" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" />
      <Association Name="Staff_Medical_Staff1" Member="Staff1" ThisKey="StaffID" OtherKey="ID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phone_Number" Member="Phone_Numbers">
    <Type Name="Phone_Number">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phone_Number_Person" Member="Persons" ThisKey="ID" OtherKey="Phone_ID" Type="Person" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PersonID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Staff_Adoption_Info" Member="Adoption_Infos" ThisKey="ID" OtherKey="StaffID" Type="Adoption_Info" />
      <Association Name="Staff_Adoption_Info1" Member="Adoption_Infos1" ThisKey="ID" OtherKey="StaffID" Type="Adoption_Info" />
      <Association Name="Staff_Intake" Member="Intakes" ThisKey="ID" OtherKey="StaffID" Type="Intake" />
      <Association Name="Staff_Intake1" Member="Intakes1" ThisKey="ID" OtherKey="StaffID" Type="Intake" />
      <Association Name="Staff_Medical_Procedure" Member="Medical_Procedures" ThisKey="ID" OtherKey="StaffID" Type="Medical_Procedure" />
      <Association Name="Staff_Medical_Procedure1" Member="Medical_Procedures1" ThisKey="ID" OtherKey="StaffID" Type="Medical_Procedure" />
      <Association Name="Staff_Medical_Staff" Member="Medical_Staffs" ThisKey="ID" OtherKey="StaffID" Type="Medical_Staff" />
      <Association Name="Staff_Medical_Staff1" Member="Medical_Staffs1" ThisKey="ID" OtherKey="StaffID" Type="Medical_Staff" />
      <Association Name="Person_Staff" Member="Person" ThisKey="PersonID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Date_Of_Birth" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SSN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Person_Customer" Member="Customers" ThisKey="ID" OtherKey="PersonID" Type="Customer" />
      <Association Name="Person_Customer1" Member="Customers1" ThisKey="ID" OtherKey="PersonID" Type="Customer" />
      <Association Name="Person_Staff" Member="Staffs" ThisKey="ID" OtherKey="PersonID" Type="Staff" />
      <Association Name="Address_Person" Member="Address" ThisKey="Address_ID" OtherKey="ID" Type="Address" IsForeignKey="true" />
      <Association Name="Address_Person1" Member="Address1" ThisKey="Address_ID" OtherKey="ID" Type="Address" IsForeignKey="true" />
      <Association Name="Phone_Number_Person" Member="Phone_Number" ThisKey="Phone_ID" OtherKey="ID" Type="Phone_Number" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Animals" Member="Animals">
    <Type Name="Animal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Species" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Breed" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Vaccinated" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SpayedorNeutered" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Food_Intake" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Room_Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Animal_Animal_Intake" Member="Animal_Intakes" ThisKey="ID" OtherKey="Animals_ID" Type="Animal_Intake" />
      <Association Name="Animal_Animal_Intake1" Member="Animal_Intakes1" ThisKey="ID" OtherKey="Animals_ID" Type="Animal_Intake" />
      <Association Name="Animal_Adoption_Status" Member="Adoption_Status" ThisKey="ID" OtherKey="Animal_ID" Type="Adoption_Status" />
      <Association Name="Animal_Adoption_Status1" Member="Adoption_Status1" ThisKey="ID" OtherKey="Animal_ID" Type="Adoption_Status" />
      <Association Name="Animal_Medical_Procedure" Member="Medical_Procedures" ThisKey="ID" OtherKey="AnimalID" Type="Medical_Procedure" />
      <Association Name="Animal_Medical_Procedure1" Member="Medical_Procedures1" ThisKey="ID" OtherKey="AnimalID" Type="Medical_Procedure" />
    </Type>
  </Table>
</Database>